### PR TITLE
Fix namespace support in view-secret

### PR DESCRIPTION
**Pull request by PeterHeja**

### CODE REVIEW

**Comment by ahmetb** [comment]
I totally wrote these plugins to have some sample plugins for http://krew.dev back in the day, they're pretty scrappy.

I realize we don't even check if ns is specified, or default to `default` namespace. It's pretty bad. If you want to rewrite this tool, let me know.

**Comment by PeterHeja** [comment]
If the namespace is not specified I think the most sane action would be to not change namespace and  execute in the one currently selected in our context.

I think this version of the namespace handling should be OK.

**Comment by elsesiy** [comment]
@ahmetb I re-wrote this in go, you can have a look [here](https://github.com/elsesiy/kubectl-decode). Let me know if you see any red flags and if not I'm happy to add it to krew!

**Comment by ahmetb** [comment]
The name “decode” won’t fly in krew. 
See krew naming guide. 
I recommend preserving either the original name or making it fit the guidelines.

**Comment by elsesiy** [comment]
> The name “decode” won’t fly in krew.
> See krew naming guide.
> I recommend preserving either the original name or making it fit the guidelines.

Sure, I'll rename it. Thank you! I'll submit it to `krew-index` later this week then

**Comment by PeterHeja** [comment]
A different PR solved this issue. I'm going to close this one.

**Pull request closed without merging**
