### PR TITLE
feat: Add option to specify container in multi-container pods

### PR DESCRIPTION
**Pull request by grzesuav**
Used https://argbash.io/ to generate template and adjusted slightly

### CODE REVIEW

**Comment by grzesuav** [comment]
I signed it!

**Comment by ahmetb** [comment]
Would you like to create a mtail repo and maintain it yourself?

I'm happy to adjust the krew plugin to point to your repo. Seems like you're on top of things more than I am wrt arg generation etc.

**Comment by grzesuav** [comment]
@ahmetb possibly would be more suitable to create some organization repo which I can try to co-maintain ? I believe that it will make easier to do not have single point of failure ;).

What do you think of this idea ?

**Comment by ahmetb** [comment]
@grzesuav honestly this repo is only plugins that I created to learn the plugin mechanism so I can go develop https://krew.dev and have some plugins to test it with.

I'm probably not going to maintain these in the long term, so if you have plans to maintain them in the long run, please extract them to your repos/orgs as you see fit and make a PR to the `krew-index` repo. I'm happy to transfer their ownership to you.

**Comment by grzesuav** [comment]
@ahmetb ok, how we will do the transfer ?

**Comment by ahmetb** [comment]
1. Fork this repo
2. Rename it
3. Fix the code or rewrite
4. Prepare releases
5. Make a pr to krew-index repository to change the url

**Comment by grzesuav** [comment]
Thanks, does the name `kubectl-mtail` will be good ? Or just `mtail` ?

**Comment by ahmetb** [comment]
I think kubectl-mtail is better. While you’re at it, consider rewriting it in a proper language :)

**Comment by grzesuav** [comment]
What do you mean ?;) like go ? 
I am also considering moving to gitlab, as they have better CI than travis, it won't be a problem for krew-index to have gitlab url?

**Comment by ahmetb** [comment]
Up to you. It would be a good test but it should work.

**Comment by grzesuav** [comment]
@ahmetb https://github.com/ahmetb/kubectl-extras/pull/7, new location is https://gitlab.com/grzesuav/kubectl-mtail

**Pull request closed without merging**
