### PR TITLE
chore: Remove mtail as moved to https://gitlab.com/grzesuav/kubectl-mtail

### PR DESCRIPTION
**Pull request by grzesuav**

### CODE REVIEW

**Comment by grzesuav** [comment]
Please **do not merge** until https://gitlab.com/grzesuav/kubectl-mtail/issues/1 is done

**Comment by ahmetb** [comment]
Krew currently doesn’t handle plugins installed but removed from the index well (there’s an open issue about it in the main repo) so we shouldn’t delete this. 

Ideal course of action would be to just have the same plugin (with the same name) point to a different repo.

**Comment by grzesuav** [comment]
Ok, thank you. Will figure something out.

**Comment by grzesuav** [comment]
@ahmetb could you check this manifests file is ok - https://gitlab.com/grzesuav/kubectl-mtail/blob/master/manifest/mtail.yaml ? It is tested on pipeline there, but just wanted to make sure if naming should remain the same.

Thank you

**Comment by ahmetb** [comment]
Feel free to make a PR to krew-index repo, you can keep the name.

**Pull request closed without merging**
